### ISSUE TITLE
Luke TODO

### ISSUE THREAD

**Issue by luke-a-rogers** [pbs-assess/pbsEDM#4]
- [x] Update output format to a list()
- [x] Add first difference and centre / scale options
- [x] Migrate pbs_smap to pbsSmap()
- [x] Confirm travis-ci working

**Comment by andrew-edwards** [comment]
So `pbsEDM()` has the lags specified as an input. The idea for the next step would be to write a wrapper function that calls that multiple times for different lags, to figure out the best embedding dimension, yes? I think so, and I can do that.

**Comment by luke-a-rogers** [comment]
> So `pbsEDM()` has the lags specified as an input. The idea for the next step would be to write a wrapper function that calls that multiple times for different lags, to figure out the best embedding dimension, yes? I think so, and I can do that.

Yes, that's what I had in mind, and should work for now. Down the road I might look at writing a separate function optimized for identifying the best dimension. It's not clear to me at this point whether searching over 'all' lags of all variables (e.g. Predator, Prey, and Salinity) makes sense, or whether its better to decide on an ecologically reasonable subset of cases first, and then only search among those (I think likely better to reduce the risk of getting high forecast accuracy by chance).

Luke

**Comment by andrew-edwards** [comment]
I just added #8, then see a similar thing in the checklist above. So I'll first try and write up the notation once and for all.
